telegram:
  token: 554095965:AAErZpDXnLO-oz9bSi-0-J0detOEG95JIBA
  source_channel: -1001537472727
  target_channel: -1001437836662
  delete_approved: true
  send_captions: true

reddit:
  client_id: XyjQjMiPSg_87TnuAK3PsQ
  client_secret: DTKHcGLb18HpcYtY4q4oploCaXaofg
  subreddits:
    - latestagecapitalism
    - socialism
    - socialism_101
    - anarchism
    - anarchy101
    - completeanarchy
    - toiletpaperusa
    - dankleft
    - antiwork
  vote_threshold: 10
  age_threshold: 86400

scheduler:
  crontab: "*/10 * * * *"