telegram:
  token: foobar
reddit:
  client_id: foo
  client_secret: bar
forwarders:
  - name: reddit-to-telegram
    interval: 1 # Every 1 minute
    from:
      type: reddit
      source:
        - /r/antiwork
        - /r/socialism
      rules:
        approve:
          votes: 10
        deny:
          age: 86400
        filter:
          type: image
    to:
      type: telegram
      target: screening-channel-id
      options:
        captions: false
        delete_chatter: true

  - name: telegram-screening
    schedule: "*/1 * * * *" # Every minute
    from:
      type: telegram
      source: screening-channel-id
      rules:
        approve:
          age: 3600
          votes: 1
        filter:
          type: image
    to:
      type: telegram
      target: main-channel
      options:
        captions: true # Of course, if there is no caption on the original, it'll still be empty

  - name: RSS
    interval: 60 # Every 60 minutes
    from:
      type: rss
      source: https://fx.substack.com/feed
      rules:
        approve:
          age: 0
        filter:
          text: world roundup
    to:
      type: telegram
      target: main-channel
      options:
        captions: true

